adapter:
  primary:
    fiber:
      port: ":8080"
      read_timeout: 5s
      write_timeout: 5s
      idle_timeout: 30s
  secondary:

infrastructure:
  jwt:
    secret_key: "aaaaaaaaaaaaSSSSSSSSSFGFFFFFRFFFFFFF"

  databases:
    postgres:
      dsn: "postgres://sandit:123123@localhost:5432/hogauth?sslmode=disable"
    redis:
      dsn: "redis://:123123@localhost:6379/0"
